  # Collector
  otel-col:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-agent-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "1777:1777"   # pprof extension
      - "8887:8888"   # Prometheus metrics exposed by the agent
      - "14268"       # Jaeger receiver
      - "55678"       # OpenCensus receiver
      - "55679:55679" # zpages extension
      - "13133"       # health_check
    depends_on:
      - otel-collector

  metrics-load-generator:
    image: golang:1.14.7
    environment:
      - GO111MODULE=on
      - OTEL_ENDPOINT=otel-agent:55678
    volumes:
      - ./otlp-load-generator/:/usr/src/
    command: ["bash", "-c", "go run /usr/src/main.go"]
    depends_on:
      - otel-col

